name: Lint
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
  ktlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          android: true
          github_token: ${{ secrets.github_token }}
          ktlint_version: "0.49.1"
          reporter: github-check
