name: Instrumented tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Run instrumented tests
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29
          arch: x86_64
          cores: 4
          disable-animations: true
          disk-size: 2048M
          emulator-options: -no-window
          heap-size: 512M
          profile: 2.7in QVGA
          script: ./gradlew connectedAndroidTest
