name: Instrumented tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run instrumented tests
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 31
          arch: x86_64
          disable-animations: true
          disk-size: 2000M
          heap-size: 600M
          script: ./gradlew connectedCheck
