name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: '17'
          distribution: 'corretto'
      - name: Run unit tests
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: check
      - name: Run instrumented tests
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: 34
          arch: arm64-v8a
          disable-animations: true
          disk-size: 2048M
          heap-size: 512M
          script: ./gradlew connectedCheck
